version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sensor-it

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - ./.data/qdrant_storage:/qdrant/storage