version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sensor-it

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - ./.data/qdrant_storage:/qdrant/storage