name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  api:
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit

  helios:
    uses: ./.github/workflows/deploy-helios.yml
    secrets: inherit