name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy_api.yml

  deploy_helios:
    uses: ./.github/workflows/deploy_helios.yml