name: CI

on:
  push:
    branches: ["main"]

jobs:
  check:
    name: Check app changed
    uses: ./.github/workflows/app-changed.yml
    with:
      app: "@sensor-it/api"
  deploy:
    needs: check
    if: needs.checks.outputs.changed == 'true'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "Deploying..."
