name: CI

on:
  push:
    branches: ["main"]

jobs:
  check:
    name: Check app changed
    uses: ./.github/workflows/app-changed.yml
    with:
      app: "@sensor-it/api"
  deploy:
    needs: check
    if: needs.checks.outputs.changed == 'true'
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun api build
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "apps/api/dist"
          target: "app/api"