name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Bun 
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check for changes
        run: bunx turbo-ignore @sensor-it/api
      - run: echo "All good!"
