name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/deploy-api.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  helios:
    uses: ./.github/workflows/deploy-helios.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}